export const SIGNUP_VIEW = 'SIGNUP_VIEW';
export const LOGIN_VIEW = 'LOGIN_VIEW';

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';

export const BACK_TO_HOME = 'BACK_TO_HOME';

export const NEW_USER_SIGNED = "NEW_USER_SIGNED";

export const LOGOUT = "LOGOUT";

export const ADD_BOOK_TO_WISHLIST_IN_STORE = "ADD_BOOK_TO_WISHLIST_IN_STORE";

export const OPEN_PUBLISH_FORM = 'OPEN_PUBLISH_FORM';
export const CLOSE_PUBLISH_FORM = 'CLOSE_PUBLISH_FORM';

export const NOTIFICATION = 'NOTIFICATION';
export const NOTIFICATION_CLOSE = 'NOTIFICATION_CLOSE';

