export const SIGNUP_VIEW = 'SIGNUP_VIEW';
export const LOGIN_VIEW = 'LOGIN_VIEW';

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';

export const BACK_TO_HOME = 'BACK_TO_HOME';

export const NEW_USER_SIGNED = "NEW_USER_SIGNED";
export const CLOSE_USER_WELCOME = 'CLOSE_USER_WELCOME';

export const LOGOUT = "LOGOUT";

export const CHAT_CREATED = 'CHAT_CREATED';

export const ADD_BOOK_TO_WISHLIST_IN_STORE = "ADD_BOOK_TO_WISHLIST_IN_STORE";

export const OPEN_PUBLISH_FORM = 'OPEN_PUBLISH_FORM';
export const CLOSE_PUBLISH_FORM = 'CLOSE_PUBLISH_FORM';

export const MAIN_LOADER_ON = 'MAIN_LOADER_ON';
export const MAIN_LOADER_OFF = 'MAIN_LOADER_OFF';

export const NOTIFICATION = 'NOTIFICATION';
export const NOTIFICATION_CLOSE = 'NOTIFICATION_CLOSE';

export const OPEN_NOTIFICATIONS_VIEW = 'OPEN_NOTIFICATIONS_VIEW';
export const CLOSE_NOTIFICATIONS_VIEW = 'CLOSE_NOTIFICATIONS_VIEW';

export const APP_MENU_OPEN = 'APP_MENU_OPEN';
export const APP_MENU_CLOSING = 'APP_MENU_CLOSING';
export const APP_MENU_CLOSE = 'APP_MENU_CLOSE';

